# ⚠️ IMPORTANT: Environment name 'dev' must match databricks.yml target name 'dev'
# This file: substitutions/dev.yaml → databricks.yml target: dev
# LHP generates resources under: resources/lhp/

# Development environment substitutions
# Token substitutions

# TODO: change to the actual catalog, schemas, and landing path
# TODO: Add any other substitution variables you need here

dev:
  env: dev
  catalog: brickwell_health_dev
  raw_schema: edw_raw
  bronze_schema: edw_bronze_claim # just being used in DB Free Edition to have everything in a single pipeline
  silver_schema: edw_silver
  gold_schema: edw_gold
  landing_path: /Volumes/brickwell_health/edw_raw/landing
  incoming_volume: /Volumes/brickwell_health_dev/edw_staging/incoming

  # Domain-specific bronze schemas
  bronze_schema_billing: edw_bronze_billing
  bronze_schema_claim: edw_bronze_claim
  bronze_schema_policy: edw_bronze_policy
  bronze_schema_regulatory: edw_bronze_regulatory
  bronze_schema_reference: edw_bronze_reference
  bronze_schema_communication: edw_bronze_communication
  bronze_schema_crm: edw_bronze_crm
  bronze_schema_digital: edw_bronze_digital
  bronze_schema_survey: edw_bronze_survey

  # Domain-specific silver schemas
  silver_schema_billing: edw_silver_billing
  silver_schema_claim: edw_silver_claim
  silver_schema_policy: edw_silver_policy

  meta_schema: _meta


# Secret configuration
# TODO: change to the actual secret scopes
# These secrets need to be created in the Databricks workspace and accessible using dbutils.secrets.get(scope, key)
# secrets:
#   default_scope: dev-secrets
#   scopes:
#     database: dev-db-secrets
#     storage: dev-storage-secrets
#     api: dev-api-secrets 